// <auto-generated />
using Code_Challenge.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Code_Challenge.Migrations
{
    [DbContext(typeof(CodeChallengeDbContext))]
    [Migration("20210907143204_COdeChallengeMigration")]
    partial class COdeChallengeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Code_Challenge.Models.People", b =>
                {
                    b.Property<string>("LdapUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAddition")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("LdapUser");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Code_Challenge.Models.Room", b =>
                {
                    b.Property<string>("RoomNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("RoomNumber");

                    b.ToTable("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
